name: Train model
description: Trains a Random Forest Regressor on the training data.
inputs:
- {name: train_csv, type: CSV}
- {name: n_estimators, type: Integer, default: '100', optional: true}
outputs:
- {name: model_pkl, type: Model}
implementation:
  container:
    image: python:3.9
    command:
    - sh
    - -c
    - (PIP_DISABLE_PIP_VERSION_CHECK=1 python3 -m pip install --quiet --no-warn-script-location
      'pandas' 'scikit-learn' 'dvc' 'dvc-s3' 'dvc-gdrive' || PIP_DISABLE_PIP_VERSION_CHECK=1
      python3 -m pip install --quiet --no-warn-script-location 'pandas' 'scikit-learn'
      'dvc' 'dvc-s3' 'dvc-gdrive' --user) && "$0" "$@"
    - sh
    - -ec
    - |
      program_path=$(mktemp)
      printf "%s" "$0" > "$program_path"
      python3 -u "$program_path" "$@"
    - |
      def _make_parent_dirs_and_return_path(file_path: str):
          import os
          os.makedirs(os.path.dirname(file_path), exist_ok=True)
          return file_path

      def train_model(
          train_csv,
          model_pkl,
          n_estimators = 100
      ):
          """
          Trains a Random Forest Regressor on the training data.
          """
          import pandas as pd
          import pickle
          from sklearn.ensemble import RandomForestRegressor

          # Load data
          train_df = pd.read_csv(train_csv)
          X_train = train_df.drop('target', axis=1)
          y_train = train_df['target']

          # Train model
          model = RandomForestRegressor(n_estimators=n_estimators, random_state=42)
          model.fit(X_train, y_train)

          # Save model artifact
          with open(model_pkl, 'wb') as f:
              pickle.dump(model, f)
          print("Model trained and saved.")

      import argparse
      _parser = argparse.ArgumentParser(prog='Train model', description='Trains a Random Forest Regressor on the training data.')
      _parser.add_argument("--train-csv", dest="train_csv", type=str, required=True, default=argparse.SUPPRESS)
      _parser.add_argument("--n-estimators", dest="n_estimators", type=int, required=False, default=argparse.SUPPRESS)
      _parser.add_argument("--model-pkl", dest="model_pkl", type=_make_parent_dirs_and_return_path, required=True, default=argparse.SUPPRESS)
      _parsed_args = vars(_parser.parse_args())

      _outputs = train_model(**_parsed_args)
    args:
    - --train-csv
    - {inputPath: train_csv}
    - if:
        cond: {isPresent: n_estimators}
        then:
        - --n-estimators
        - {inputValue: n_estimators}
    - --model-pkl
    - {outputPath: model_pkl}
